runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
  - name: ssl
    version: latest

skip_files:
- /home/tushar/Documents/Flask/FirstTry/fvenv/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m-pic.a
